### ISSUE TITLE
Building sample applications failed with Streams 4.2

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.cybersecurity.starterApps#1]
ant all for DomainProfilingSamples:
[echo] Compiling application...
     [exec] com.ibm.streamsx.cybersecurity.sample/DomainProfilingBasic.spl:22:21: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: answerData.
     [exec] com.ibm.streamsx.cybersecurity.sample/DomainProfilingBasic.spl:22:33: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: additionalData.

**Comment by cancilla** [comment]
The master branch now contains samples that will compile with the version of the toolkit that ships with Streams 4.2.
